[project]
name = "publish-spl"
authors = ["SPL Developer Team"]
description = "A decentralized publishing platform for tracking and monetizing digital content rights on the Stacks blockchain"
telemetry = false
requirements = []

[contracts.spl-registry]
path = "contracts/spl-registry.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
